[package]
name = "challenge6"
version = "0.1.0"
authors = ["Daniel Abeledo <daniel.abeledo@gmail.com>"]
edition = "2018"

[dependencies]
base64 = {version = "^0", path = "../../base64/"}
linked-hash-map = "0.5.3"
ndarray = "0.13.1"